### ISSUE TITLE
Vidyo > User/Login issues

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [atoddj/workflow#1]
Want to keep the spacing next to the site URL's common

so not

- CHS
  -Vitelnet
  -DH
-DH 

but 

-  Vitel
-  CHS
-  ETC

**Comment by atoddj** [comment]
This has been implemented. 
https://atoddj.github.io/workflow/#/vidyo/user-login-issue

**Comment by BrickerBrickerOneNine** [comment]
Its fine with the "Letters" on the left, but i want there to be uniformed spacing for the beginning of the URLS. so

CHS        https://
Vitelnet   https://
ETC         https://

**Comment by BrickerBrickerOneNine** [comment]
well, that spacing didn't stick. wtf. um
